version: '3'
services:
  web:
    build:
      context: ./service/web
    ports:
    - '${HOST_PORT_HTTP}:80'
    - '${HOST_PORT_HTTPS}:443'
    volumes:
    - ./src:/var/www/html
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - '${HOST_PORT_MYSQL}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
    - ./service/mysql/init:/docker-entrypoint-initdb.d